@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzU3NTc3MTAxLCJpYXQiOjE3NTc1NzM1MDF9.7_WkEDzpZmTFKzdNt6bFkHMhhAMoQN5c7_Z3wo3oGLs
### Login

POST http://localhost:8080/admin/employee/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

### Create Employee (Requires Auth)

POST http://localhost:8080/admin/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 0,
    "idNumber": "111222333444555666",
    "name": "zhi",
    "phone": "13812344321",
    "sex": "1",
    "username": "小智"
}

###

GET http://localhost:8080/admin/employee/page?page=1&pageSize=10
Authorization: Bearer {{token}}

### Change Employee Status (Requires Auth)

POST http://localhost:8080/admin/employee/status/1?id=3
Authorization: Bearer {{token}}

### Get Employee by ID (Requires Auth)

GET http://localhost:8080/admin/employee/3
Authorization: Bearer {{token}}

### Update Employee (Requires Auth)

PUT http://localhost:8080/admin/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 3,
    "idNumber": "111222333444555666",
    "name": "小智1",
    "phone": "13812344321",
    "sex": "1",
    "username": "zhi-updated"
}

### Add Category (Requires Auth)
### the interface is not working properly because of the type issue
### fixed by changing type from String to i32 in CategoryDto and using deserialize_with in Category entity
### so the string input can be deserialized to i32. fuck
POST http://localhost:8080/admin/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "bun",
    "type": 1,
    "sort": "10"
}

### Get Category Page (Requires Auth)
GET http://localhost:8080/admin/category/page?page=1&pageSize=10
Authorization: Bearer {{token}}

### Update Category (Requires Auth)
PUT http://localhost:8080/admin/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 1,
    "name": "bun-updated",
    "sort": "10"
}

### Get Category by ID (Requires Auth)
GET http://localhost:8080/admin/category

Authorization: Bearer {{token}}/1

### Delete Category by ID (Requires Auth)
DELETE http://localhost:8080/admin/category/1
Authorization: Bearer {{token}}