@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzU3NTE5MDA4LCJpYXQiOjE3NTc1MTU0MDh9.Kjs-i2yDrSC5ITNFK1WplaB8b44RXzT0mUbnlvMP1D8
### Login

POST http://localhost:8080/admin/employee/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

### Create Employee (Requires Auth)

POST http://localhost:8080/admin/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 0,
    "idNumber": "111222333444555666",
    "name": "zhi",
    "phone": "13812344321",
    "sex": "1",
    "username": "小智"
}

###

GET http://localhost:8080/admin/employee/page?page=1&pageSize=10
Authorization: Bearer {{token}}

### Change Employee Status (Requires Auth)

POST http://localhost:8080/admin/employee/status/1?id=3
Authorization: Bearer {{token}}

### Get Employee by ID (Requires Auth)

GET http://localhost:8080/admin/employee/3
Authorization: Bearer {{token}}

### Update Employee (Requires Auth)

PUT http://localhost:8080/admin/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 3,
    "idNumber": "111222333444555666",
    "name": "小智1",
    "phone": "13812344321",
    "sex": "1",
    "username": "zhi-updated"
}