//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod address_book;
pub mod category;
pub mod dish;
pub mod dish_flavor;
pub mod employee;
pub mod order_detail;
pub mod orders;
pub mod setmeal;
pub mod setmeal_dish;
pub mod shopping_cart;
pub mod user;
