//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub number: Option<String>,
    pub status: i32,
    pub user_id: i64,
    pub address_book_id: i64,
    pub order_time: DateTime,
    pub checkout_time: Option<DateTime>,
    pub pay_method: i32,
    pub pay_status: i16,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub amount: Decimal,
    pub remark: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub user_name: Option<String>,
    pub consignee: Option<String>,
    pub cancel_reason: Option<String>,
    pub rejection_reason: Option<String>,
    pub cancel_time: Option<DateTime>,
    pub estimated_delivery_time: Option<DateTime>,
    pub delivery_status: i16,
    pub delivery_time: Option<DateTime>,
    pub pack_amount: Option<i32>,
    pub tableware_number: Option<i32>,
    pub tableware_status: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
