//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::address_book::Entity as AddressBook;
pub use super::category::Entity as Category;
pub use super::dish::Entity as Dish;
pub use super::dish_flavor::Entity as DishFlavor;
pub use super::employee::Entity as Employee;
pub use super::order_detail::Entity as OrderDetail;
pub use super::orders::Entity as Orders;
pub use super::setmeal::Entity as Setmeal;
pub use super::setmeal_dish::Entity as SetmealDish;
pub use super::shopping_cart::Entity as ShoppingCart;
pub use super::user::Entity as User;
